# Ported from playwright-repo-test/lib/codegen.js — adapted for agent/
from __future__ import annotations

import json
import re
from typing import Any

from agent.stepgraph.models import Step, StepGraph

_LOCATOR_ACTIONS = {
    "assert_checked",
    "assert_count",
    "assert_enabled",
    "assert_hidden",
    "assert_in_viewport",
    "assert_text",
    "assert_value",
    "assert_visible",
    "check",
    "click",
    "drag",
    "fill",
    "focus",
    "hover",
    "select",
    "type",
    "uncheck",
    "upload",
}


def build_playwright_codegen_artifacts(
    step_graph: StepGraph,
    *,
    test_name: str = "recorded user flow",
    target_url: str | None = None,
) -> dict[str, Any]:
    """Build both code artifacts:
    - preview_code: single-file runnable spec (default Code tab UX)
    - package_files: framework-style POM package files (secondary download UX)
    """
    preview_code = build_playwright_test_source(
        step_graph,
        test_name=test_name,
        target_url=target_url,
    )
    package_files = build_playwright_pom_package_files(
        step_graph,
        test_name=test_name,
        target_url=target_url,
    )
    return {
        "preview_code": preview_code,
        "package_files": package_files,
    }


def build_playwright_test_source(
    step_graph: StepGraph,
    *,
    test_name: str = "recorded user flow",
    target_url: str | None = None,
) -> str:
    resolved_url = target_url or _infer_target_url(step_graph) or "about:blank"
    locator_map = _build_locator_map(step_graph)
    locator_entries = _render_locator_map_with_labels(step_graph, locator_map)

    lines = [
        f"// {test_name}",
        "// Auto-generated by Playwright Agent — safe to edit.",
        "import { test, expect, Page } from '@playwright/test';",
        "",
        "// Override start URL at runtime: BASE_URL=https://your-app.com npx playwright test",
        f"const START_URL = process.env.BASE_URL || {_ts_string(resolved_url if resolved_url != 'about:blank' else '')};",
        "",
        "// Locators: primary selector first, fallbacks after.",
        "// Update these when selectors change in your app.",
        "const LOCATORS: Record<string, string[]> = {",
    ]
    lines.extend(locator_entries)
    lines.append("};")
    lines.append("")
    lines.extend([
        "// Tries each selector in order, returns the first one found on the page.",
        "async function resolveLocator(page: Page, key: string) {",
        "  const candidates = LOCATORS[key] ?? [];",
        "  if (!candidates.length) throw new Error(`No locators defined for: ${key}`);",
        "  for (const selector of candidates) {",
        "    const el = page.locator(selector);",
        "    if ((await el.count()) > 0) return el.first();",
        "  }",
        "  return page.locator(candidates[0]).first();",
        "}",
        "",
        f"test({_ts_string(test_name)}, async ({'{'} page {'}'}) => {{",
        "  if (START_URL) await page.goto(START_URL, { waitUntil: 'domcontentloaded' });",
        "",
    ])

    for index, step in enumerate(step_graph.steps, start=1):
        lines.extend(_render_step(step=step, step_number=index))

    lines.append("});")
    return "\n".join(lines)


def _render_step(*, step: Step, step_number: int) -> list[str]:
    action = step.action.strip().lower()
    lines = _render_step_comment(step=step, step_number=step_number, indent="  ")
    metadata = _step_data(step)
    timeout_ms = max(step.timeout_policy.timeout_ms, 0)

    if action == "navigate":
        url = _pick_string(metadata, "url", "targetUrl", "navigateUrl", "sourceUrl")
        if url:
            lines.append(f"  await page.goto({_ts_string(url)}, {{ waitUntil: 'domcontentloaded' }});")
        else:
            lines.append("  // TODO: navigate step missing URL — set the URL here.")
        lines.append("")
        return lines

    if action == "navigate_back":
        lines.append("  await page.goBack();")
        lines.append("")
        return lines

    if action == "wait_timeout":
        wait_ms = _pick_int(metadata, "timeoutMs", "waitMs", "ms") or timeout_ms
        lines.append(f"  await page.waitForTimeout({wait_ms});")
        lines.append("")
        return lines

    if action == "wait_for":
        url_pattern = _pick_string(metadata, "urlPattern", "url")
        text = _pick_string(metadata, "text", "expected")
        selector = _pick_string(metadata, "selector", "locator", "target")
        if url_pattern:
            lines.append(f"  await page.waitForURL({_ts_string(url_pattern)}, {{ timeout: {timeout_ms or 30_000} }});")
        elif text:
            lines.append(f"  await expect(page.locator('body')).toContainText({_ts_string(text)}, {{ timeout: {timeout_ms or 30_000} }});")
        elif selector:
            lines.append(f"  await page.locator({_ts_string(selector)}).first().waitFor({{ state: 'visible', timeout: {timeout_ms or 30_000} }});")
        else:
            lines.append(f"  await page.waitForTimeout({timeout_ms or 1_000});")
        lines.append("")
        return lines

    if action == "dialog_handle":
        accept = _pick_bool(metadata, "accept", "dialogAccept", default=True)
        prompt_text = _pick_string(metadata, "promptText", "prompt", "text", "value")
        if accept:
            if prompt_text is None:
                lines.append("  page.once('dialog', dialog => dialog.accept());")
            else:
                lines.append(f"  page.once('dialog', dialog => dialog.accept({_ts_string(prompt_text)}));")
        else:
            lines.append("  page.once('dialog', dialog => dialog.dismiss());")
        lines.append("")
        return lines

    if action == "js_execute":
        js_code = _pick_string(metadata, "js_code", "jsCode")
        if js_code:
            lines.append("  await page.evaluate(async () => {")
            for raw_line in js_code.splitlines():
                lines.append(f"    {raw_line}")
            lines.append("  });")
        else:
            lines.append("  throw new Error('js_execute step is missing js_code.');")
        lines.append("")
        return lines

    if action in {"expect_new_tab", "switch_tab", "close_tab", "frame_enter", "frame_exit"}:
        lines.append(f"  // TODO: '{action}' requires manual tab/frame handling in your test framework.")
        lines.append("")
        return lines

    if action in {"assert_url", "assert_title"}:
        expected = _pick_string(metadata, "urlPattern", "url", "titlePattern", "title", "expected")
        if expected is None:
            lines.append("  throw new Error('Assertion step missing expected value.');")
        elif action == "assert_url":
            lines.append(f"  await expect(page).toHaveURL({_ts_string(expected)}, {{ timeout: {timeout_ms or 30_000} }});")
        else:
            lines.append(f"  await expect(page).toHaveTitle({_ts_string(expected)}, {{ timeout: {timeout_ms or 30_000} }});")
        lines.append("")
        return lines

    if action in _LOCATOR_ACTIONS:
        if step.target is None:
            lines.append("  throw new Error('This step has no element target recorded.');")
            lines.append("")
            return lines
        lines.append(f"  const el{step_number} = await resolveLocator(page, {_ts_string(step.step_id)});")

    lines.extend(
        _render_locator_action(
            action=action,
            metadata=metadata,
            timeout_ms=timeout_ms,
            locator_var=f"el{step_number}",
        )
    )
    lines.append("")
    return lines


def _render_locator_action(
    *,
    action: str,
    metadata: dict[str, Any],
    timeout_ms: int,
    locator_var: str,
) -> list[str]:
    timeout = timeout_ms or 30_000
    if action == "click":
        return [f"  await {locator_var}.click({{ timeout: {timeout} }});"]
    if action == "fill":
        value = _pick_string(metadata, "text", "value", "fillVal") or ""
        return [f"  await {locator_var}.fill({_ts_string(value)}, {{ timeout: {timeout} }});"]
    if action == "type":
        value = _pick_string(metadata, "text", "typeText", "value") or ""
        return [
            f"  await {locator_var}.pressSequentially({_ts_string(value)}, {{ delay: 50, timeout: {timeout} }});"
        ]
    if action == "press":
        key = _pick_string(metadata, "key", "value") or "Enter"
        return [f"  await page.keyboard.press({_ts_string(key)});"]
    if action == "check":
        return [f"  await {locator_var}.check({{ timeout: {timeout} }});"]
    if action == "uncheck":
        return [f"  await {locator_var}.uncheck({{ timeout: {timeout} }});"]
    if action == "select":
        value = _pick_string(metadata, "value", "selectValue", "option") or ""
        return [f"  await {locator_var}.selectOption({_ts_string(value)}, {{ timeout: {timeout} }});"]
    if action == "upload":
        path = _pick_string(metadata, "filePath", "path", "value", "filePaths") or ""
        return [f"  await {locator_var}.setInputFiles({_ts_string(path)});"]
    if action == "drag":
        source = _pick_string(metadata, "sourceSelector", "sourcePrimarySelector")
        if source is None:
            return ["  throw new Error('Drag step missing source selector metadata.');"]
        return [
            f"  await page.locator({_ts_string(source)}).first().dragTo({locator_var}, {{ timeout: {timeout} }});"
        ]
    if action == "hover":
        return [f"  await {locator_var}.hover({{ timeout: {timeout} }});"]
    if action == "focus":
        return [f"  await {locator_var}.focus({{ timeout: {timeout} }});"]
    if action == "assert_visible":
        return [f"  await expect({locator_var}).toBeVisible({{ timeout: {timeout} }});"]
    if action == "assert_text":
        expected = _pick_string(metadata, "expected", "text", "value") or ""
        contains = _pick_bool(metadata, "contains", default=True)
        matcher = "toContainText" if contains else "toHaveText"
        return [f"  await expect({locator_var}).{matcher}({_ts_string(expected)}, {{ timeout: {timeout} }});"]
    if action == "assert_value":
        expected = _pick_string(metadata, "expected", "expectedValue", "value") or ""
        return [f"  await expect({locator_var}).toHaveValue({_ts_string(expected)}, {{ timeout: {timeout} }});"]
    if action == "assert_checked":
        expected_checked = _pick_bool(metadata, "expected", "expectedChecked", default=True)
        if expected_checked:
            return [f"  await expect({locator_var}).toBeChecked({{ timeout: {timeout} }});"]
        return [f"  await expect({locator_var}).not.toBeChecked({{ timeout: {timeout} }});"]
    if action == "assert_enabled":
        expected_enabled = _pick_bool(metadata, "expected", "expectedEnabled", default=True)
        if expected_enabled:
            return [f"  await expect({locator_var}).toBeEnabled({{ timeout: {timeout} }});"]
        return [f"  await expect({locator_var}).toBeDisabled({{ timeout: {timeout} }});"]
    if action == "assert_hidden":
        return [f"  await expect({locator_var}).toBeHidden({{ timeout: {timeout} }});"]
    if action == "assert_count":
        count = _pick_int(metadata, "expectedCount", "count")
        return [f"  await expect({locator_var}).toHaveCount({count or 0}, {{ timeout: {timeout} }});"]
    if action == "assert_in_viewport":
        return [f"  await expect({locator_var}).toBeInViewport({{ timeout: {timeout} }});"]
    return [f"  throw new Error('Unsupported step action: {action}');"]


def build_playwright_pom_package_files(
    step_graph: StepGraph,
    *,
    test_name: str = "recorded user flow",
    target_url: str | None = None,
) -> dict[str, str]:
    resolved_url = target_url or _infer_target_url(step_graph) or "about:blank"
    slug = _slugify(test_name) or "recorded-user-flow"
    class_name = "GeneratedFlowPage"
    page_file = f"pages/{class_name}.ts"
    spec_file = f"tests/{slug}.spec.ts"
    handoff = _build_handoff_payload(step_graph=step_graph, class_name=class_name, test_name=test_name)

    files = {
        page_file: _render_page_object_source(
            step_graph=step_graph,
            class_name=class_name,
            start_url=resolved_url,
        ),
        spec_file: _render_spec_source(
            step_graph=step_graph,
            class_name=class_name,
            test_name=test_name,
            page_file=page_file,
        ),
        "support/locatorResolver.ts": _render_locator_resolver_source(),
        "playwright.config.ts": _render_playwright_config_source(),
        "tsconfig.json": _render_tsconfig_source(),
        "package.json": _render_package_json_source(),
        "README.generated.md": _render_generated_readme(
            step_graph=step_graph,
            test_name=test_name,
            spec_file=spec_file,
            page_file=page_file,
        ),
        "handoff.generated.json": json.dumps(handoff, indent=2, ensure_ascii=True),
    }
    return files


def _render_page_object_source(*, step_graph: StepGraph, class_name: str, start_url: str) -> str:
    locator_map = _build_locator_map(step_graph)
    locator_entries = _render_locator_map_with_labels(step_graph, locator_map)
    lines = [
        "import { Page, Locator, expect } from '@playwright/test';",
        "import { resolveLocator } from '../support/locatorResolver';",
        "",
        f"export class {class_name} {{",
        "  constructor(private readonly page: Page) {}",
        "",
        "  // Locators: primary selector first, fallbacks after.",
        "  // Replace these with stable selectors (data-testid, role, label) as you refactor.",
        "  private readonly locators: Record<string, string[]> = {",
    ]
    lines.extend(f"  {entry}" for entry in locator_entries)
    lines.extend([
        "  };",
        "",
        "  private async el(key: string): Promise<Locator> {",
        "    return resolveLocator(this.page, this.locators[key] ?? [], key);",
        "  }",
        "",
        "  async goto(): Promise<void> {",
        f"    const url = process.env.BASE_URL || {_ts_string(start_url if start_url != 'about:blank' else '')};",
        "    if (url) await this.page.goto(url, { waitUntil: 'domcontentloaded' });",
        "  }",
        "",
    ])
    for idx, step in enumerate(step_graph.steps, start=1):
        lines.extend(_render_page_method(step=step, step_number=idx))
    lines.append("}")
    return "\n".join(lines)


def _render_page_method(*, step: Step, step_number: int) -> list[str]:
    method_name = _method_name(step.action, step_number)
    action = step.action.strip().lower()
    metadata = _step_data(step)
    timeout_ms = max(step.timeout_policy.timeout_ms, 0) or 30_000

    out = _render_step_comment(step=step, step_number=step_number, indent="  ")
    out.append(f"  async {method_name}(): Promise<void> {{")


    if action in _LOCATOR_ACTIONS:
        out.append(f"    const el = await this.el({_ts_string(step.step_id)});")

    if action == "navigate":
        url = _pick_string(metadata, "url", "targetUrl", "navigateUrl", "sourceUrl")
        if url:
            out.append(f"    await this.page.goto({_ts_string(url)}, {{ waitUntil: 'domcontentloaded' }});")
        else:
            out.append("    throw new Error('Navigate step is missing a URL.');")
    elif action == "navigate_back":
        out.append("    await this.page.goBack();")
    elif action == "wait_timeout":
        wait_ms = _pick_int(metadata, "timeoutMs", "waitMs", "ms") or timeout_ms
        out.append(f"    await this.page.waitForTimeout({wait_ms});")
    elif action == "wait_for":
        url_pattern = _pick_string(metadata, "urlPattern", "url")
        text = _pick_string(metadata, "text", "expected")
        selector = _pick_string(metadata, "selector", "locator", "target")
        if url_pattern:
            out.append(f"    await this.page.waitForURL({_ts_string(url_pattern)}, {{ timeout: {timeout_ms} }});")
        elif text:
            out.append(f"    await expect(this.page.locator('body')).toContainText({_ts_string(text)}, {{ timeout: {timeout_ms} }});")
        elif selector:
            out.append(f"    await this.page.locator({_ts_string(selector)}).first().waitFor({{ state: 'visible', timeout: {timeout_ms} }});")
        else:
            out.append(f"    await this.page.waitForTimeout({timeout_ms});")
    elif action == "dialog_handle":
        accept = _pick_bool(metadata, "accept", "dialogAccept", default=True)
        prompt_text = _pick_string(metadata, "promptText", "prompt", "text", "value")
        if accept and prompt_text is None:
            out.append("    this.page.once('dialog', dialog => dialog.accept());")
        elif accept:
            out.append(f"    this.page.once('dialog', dialog => dialog.accept({_ts_string(prompt_text)}));")
        else:
            out.append("    this.page.once('dialog', dialog => dialog.dismiss());")
    elif action == "js_execute":
        js_code = _pick_string(metadata, "js_code", "jsCode")
        if js_code:
            out.append("    await this.page.evaluate(async () => {")
            for raw_line in js_code.splitlines():
                out.append(f"      {raw_line}")
            out.append("    });")
        else:
            out.append("    throw new Error('js_execute step is missing js_code.');")
    elif action in {"assert_url", "assert_title"}:
        expected = _pick_string(metadata, "urlPattern", "url", "titlePattern", "title", "expected")
        if expected is None:
            out.append("    throw new Error('Assertion step missing expected value.');")
        elif action == "assert_url":
            out.append(f"    await expect(this.page).toHaveURL({_ts_string(expected)}, {{ timeout: {timeout_ms} }});")
        else:
            out.append(f"    await expect(this.page).toHaveTitle({_ts_string(expected)}, {{ timeout: {timeout_ms} }});")
    elif action in {"expect_new_tab", "switch_tab", "close_tab", "frame_enter", "frame_exit"}:
        out.append(f"    // TODO: '{action}' requires manual tab/frame handling.")
        out.append(f"    throw new Error('Manual handling required: {action}');")
    else:
        for line in _render_locator_action(
            action=action,
            metadata=metadata,
            timeout_ms=timeout_ms,
            locator_var="el",
        ):
            out.append(f"    {line.strip()}")

    out.append("  }")
    out.append("")
    return out


def _render_spec_source(
    *,
    step_graph: StepGraph,
    class_name: str,
    test_name: str,
    page_file: str,
) -> str:
    rel_page_import = "../" + page_file.replace(".ts", "")
    lines = [
        "import { test } from '@playwright/test';",
        f"import {{ {class_name} }} from '{rel_page_import}';",
        "",
        f"test({_ts_string(test_name)}, async ({'{'} page {'}'}) => {{",
        f"  const flow = new {class_name}(page);",
    ]
    if not _has_recorded_navigation(step_graph):
        lines.append("  await flow.goto();")
    for idx, step in enumerate(step_graph.steps, start=1):
        lines.append(f"  await flow.{_method_name(step.action, idx)}();")
    lines.extend(["});", ""])
    return "\n".join(lines)


def _render_locator_resolver_source() -> str:
    return "\n".join(
        [
            "import { Locator, Page } from '@playwright/test';",
            "",
            "// Keeps generated POM methods stable while selectors are hardened by humans.",
            "// The first locator is the recorded primary selector; later entries are fallbacks.",
            "export async function resolveLocator(",
            "  page: Page,",
            "  candidates: string[],",
            "  stepId: string,",
            "): Promise<Locator> {",
            "  if (!candidates.length) {",
            "    throw new Error(`No locator candidates configured for ${stepId}`);",
            "  }",
            "  for (const selector of candidates) {",
            "    const candidate = page.locator(selector).first();",
            "    try {",
            "      if (await candidate.count()) {",
            "        return candidate;",
            "      }",
            "    } catch {",
            "      // continue trying fallback selectors",
            "    }",
            "  }",
            "  return page.locator(candidates[0]).first();",
            "}",
            "",
        ]
    )


def _render_playwright_config_source() -> str:
    return "\n".join(
        [
            "import { defineConfig, devices } from '@playwright/test';",
            "",
            "export default defineConfig({",
            "  testDir: './tests',",
            "  fullyParallel: false,",
            "  retries: process.env.CI ? 2 : 0,",
            "  reporter: process.env.CI ? 'github' : 'list',",
            "  use: {",
            "    headless: process.env.HEADLESS ? process.env.HEADLESS !== 'false' : !!process.env.CI,",
            "    viewport: { width: 1280, height: 720 },",
            "    screenshot: 'only-on-failure',",
            "    trace: 'retain-on-failure',",
            "  },",
            "  projects: [",
            "    { name: 'chromium', use: { ...devices['Desktop Chrome'] } },",
            "  ],",
            "});",
            "",
        ]
    )


def _render_tsconfig_source() -> str:
    config = {
        "compilerOptions": {
            "target": "ES2020",
            "module": "commonjs",
            "lib": ["ES2020"],
            "types": ["node"],
            "strict": True,
            "esModuleInterop": True,
            "moduleResolution": "node",
            "resolveJsonModule": True,
            "outDir": "dist",
            "rootDir": ".",
        },
        "include": ["**/*.ts"],
        "exclude": ["node_modules", "dist"],
    }
    return json.dumps(config, indent=2, ensure_ascii=True) + "\n"


def _render_package_json_source() -> str:
    pkg = {
        "name": "playwright-generated-flow",
        "private": True,
        "version": "1.0.0",
        "scripts": {
            "test": "playwright test",
            "test:headed": "HEADLESS=false playwright test --headed",
            "typecheck": "tsc --noEmit",
        },
        "devDependencies": {
            "@playwright/test": "^1.53.0",
            "@types/node": "^22.15.21",
            "typescript": "^5.8.3",
        },
    }
    return json.dumps(pkg, indent=2, ensure_ascii=True) + "\n"


def _render_generated_readme(
    *,
    step_graph: StepGraph,
    test_name: str,
    spec_file: str,
    page_file: str,
) -> str:
    return "\n".join(
        [
            "# Generated Playwright Package",
            "",
            f"- Run ID: `{step_graph.run_id}`",
            f"- Test name: `{test_name}`",
            "",
            "## Files",
            f"- `{spec_file}`",
            f"- `{page_file}`",
            "- `support/locatorResolver.ts`",
            "- `playwright.config.ts`",
            "- `tsconfig.json`",
            "- `package.json`",
            "- `handoff.generated.json`",
            "",
            "## Run",
            "```bash",
            "npm install",
            "npx playwright install",
            "npm run typecheck",
            "BASE_URL='https://example.com' npx playwright test",
            "```",
            "",
            "## Notes",
            "- Tests are generated from recorded steps.",
            "- The page object keeps each recorded step as a named method so teams can review, rename, and refactor safely.",
            "- Locator arrays keep the recorded primary selector first and fallback selectors after it.",
            "- Tab/frame specific steps may require manual orchestration in your framework.",
            "",
        ]
    )


def _build_handoff_payload(*, step_graph: StepGraph, class_name: str, test_name: str) -> dict[str, Any]:
    steps: list[dict[str, Any]] = []
    for idx, step in enumerate(step_graph.steps, start=1):
        steps.append(
            {
                "stepId": step.step_id,
                "action": step.action,
                "methodName": _method_name(step.action, idx),
                "pageClass": class_name,
                "locators": _build_locator_map_for_step(step),
                "metadata": _step_data(step),
            }
        )
    return {
        "formatVersion": "1.0",
        "runId": step_graph.run_id,
        "testName": test_name,
        "pageClass": class_name,
        "steps": steps,
    }


def _infer_target_url(step_graph: StepGraph) -> str | None:
    for step in step_graph.steps:
        if step.action.strip().lower() != "navigate":
            continue
        metadata = _step_data(step)
        url = _pick_string(metadata, "url", "targetUrl", "navigateUrl", "sourceUrl")
        if url:
            return url
    return None


def _has_recorded_navigation(step_graph: StepGraph) -> bool:
    return any(step.action.strip().lower() == "navigate" for step in step_graph.steps)


def _build_locator_map(step_graph: StepGraph) -> dict[str, list[str]]:
    locator_map: dict[str, list[str]] = {}
    for step in step_graph.steps:
        if step.target is None:
            continue
        selectors = [step.target.primary_selector] + list(step.target.fallback_selectors)
        deduped: list[str] = []
        seen: set[str] = set()
        for selector in selectors:
            value = selector.strip()
            if not value or value in seen:
                continue
            seen.add(value)
            deduped.append(value)
        if deduped:
            locator_map[step.step_id] = deduped
    return locator_map


def _pick_string(metadata: dict[str, Any], *keys: str) -> str | None:
    for key in keys:
        value = metadata.get(key)
        if isinstance(value, list):
            for item in value:
                if isinstance(item, str) and item.strip():
                    return item.strip()
        if isinstance(value, str) and value.strip():
            return value.strip()
    return None


def _pick_int(metadata: dict[str, Any], *keys: str) -> int | None:
    for key in keys:
        value = metadata.get(key)
        if isinstance(value, int):
            return value
        if isinstance(value, str) and value.strip().isdigit():
            return int(value.strip())
    return None


def _pick_bool(metadata: dict[str, Any], *keys: str, default: bool) -> bool:
    for key in keys:
        if key not in metadata:
            continue
        value = metadata[key]
        if isinstance(value, bool):
            return value
        if isinstance(value, str):
            lowered = value.strip().lower()
            if lowered in {"true", "1", "yes"}:
                return True
            if lowered in {"false", "0", "no"}:
                return False
    return default


def _step_data(step: Step) -> dict[str, Any]:
    metadata = step.metadata if isinstance(step.metadata, dict) else {}
    flattened: dict[str, Any] = {}
    params = metadata.get("params")
    if isinstance(params, dict):
        flattened.update(params)
    flattened.update(metadata)
    return flattened


def _build_locator_map_for_step(step: Step) -> list[str]:
    if step.target is None:
        return []
    selectors = [step.target.primary_selector, *step.target.fallback_selectors]
    out: list[str] = []
    seen: set[str] = set()
    for selector in selectors:
        clean = selector.strip()
        if not clean or clean in seen:
            continue
        seen.add(clean)
        out.append(clean)
    return out


def _render_locator_map_with_labels(
    step_graph: StepGraph,
    locator_map: dict[str, list[str]],
) -> list[str]:
    """Render the LOCATORS map with a rich comment above each entry."""
    step_index: dict[str, tuple[int, Step]] = {}
    for idx, step in enumerate(step_graph.steps, start=1):
        step_index[step.step_id] = (idx, step)

    lines: list[str] = []
    for step_id, selectors in locator_map.items():
        if step_id in step_index:
            idx, step = step_index[step_id]
            action = step.action.strip().lower()
            hint = _element_hint(step)
            comment = f"Step {idx} — {action}"
            if hint:
                comment += f" | {hint}"
        else:
            comment = step_id
        selectors_json = json.dumps(selectors, ensure_ascii=True)
        lines.append(f"  // {comment}")
        lines.append(f"  {json.dumps(step_id)}: {selectors_json},")
    return lines


def _render_step_comment(*, step: Step, step_number: int, indent: str) -> list[str]:
    """Multi-line comment block above each step — useful for humans and LLM refactoring."""
    action = step.action.strip().lower()
    hint = _element_hint(step)
    metadata = _step_data(step)

    # Line 1: step number, action, element identity
    first = f"Step {step_number} — {action}"
    if hint:
        first += f" | {hint}"

    # Line 2: page URL context (helps LLM decide which Page class this belongs to)
    page_url = _pick_string(metadata, "pageUrl", "sourceUrl", "url") or ""
    # for navigate steps the url IS the target, not the page context — skip it there
    if action == "navigate":
        page_url = ""

    lines = [f"{indent}// {first}"]
    if page_url:
        lines.append(f"{indent}// page: {page_url}")

    # Line 3: reasoning hint from locator engine (explains why this selector was chosen)
    if step.target and step.target.reasoning_hint:
        lines.append(f"{indent}// locator note: {step.target.reasoning_hint}")

    return lines


def _element_hint(step: Step) -> str:
    """Short human-readable element identity string from descriptor metadata."""
    metadata = _step_data(step)
    descriptor: dict[str, Any] = metadata.get("descriptor") or {}

    parts: list[str] = []
    tag = descriptor.get("tag", "")
    role = descriptor.get("role", "")
    aria = descriptor.get("ariaLabel", "")
    testid = descriptor.get("testid", "")
    placeholder = descriptor.get("placeholder", "")
    text = descriptor.get("text", "")
    input_type = descriptor.get("inputType", "")
    el_id = descriptor.get("id", "")

    if tag:
        label = tag
        if input_type:
            label += f"[type={input_type}]"
        elif role:
            label += f"[role={role}]"
        parts.append(label)

    if aria:
        parts.append(f'aria-label="{aria}"')
    elif testid:
        parts.append(f'data-testid="{testid}"')
    elif placeholder:
        parts.append(f'placeholder="{placeholder}"')
    elif el_id:
        parts.append(f'id="{el_id}"')
    elif text:
        snippet = text[:40].strip()
        if snippet:
            parts.append(f'text="{snippet}"')

    return " | ".join(parts)


def _method_name(action: str, step_number: int) -> str:
    safe = re.sub(r"[^a-zA-Z0-9_]+", "_", (action or "step").strip().lower()).strip("_")
    safe = safe or "step"
    return f"step{step_number}_{safe}"


def _slugify(value: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9]+", "-", (value or "").strip().lower()).strip("-")
    return slug


def _ts_string(value: str) -> str:
    escaped = (
        value.replace("\\", "\\\\")
        .replace("'", "\\'")
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )
    return f"'{escaped}'"
