// recorded user flow
// Auto-generated by Playwright Agent — safe to edit.
import { test, expect, Page } from '@playwright/test';

// Override start URL at runtime: BASE_URL=https://your-app.com npx playwright test
const START_URL = process.env.BASE_URL || '';

// Locators: primary selector first, fallbacks after.
// Update these when selectors change in your app.
const LOCATORS: Record<string, string[]> = {
  // Step 1 — click | p | text="Find out where you stand among peers"
  "step_01KQ4YMNNNHP2XBSNJ2R7DNS24": ["p:has-text(\"Find out where you stand among peers\")", "xpath=/html/body/section/div/div/div/div[3]/div[2]/p"],
  // Step 2 — click | img | id="MzIwMToxOTg=-1"
  "step_01KQ4YMQKYF6V6BA3FR4QE1HZQ": ["xpath=//*[@id=\"MzIwMToxOTg=-1\"]"],
  // Step 3 — click | html | text="We use cookies to enable the best possib"
  "step_01KQ4YN1J1J6TDCM6RX06H1E3R": ["xpath=/html"],
  // Step 4 — click | path | id="Icon_material-close"
  "step_01KQ4YN343AAVMTCSFDRAXJF6X": ["#Icon_material-close >> nth=0"],
};

// Tries each selector in order, returns the first one found on the page.
async function resolveLocator(page: Page, key: string) {
  const candidates = LOCATORS[key] ?? [];
  if (!candidates.length) throw new Error(`No locators defined for: ${key}`);
  for (const selector of candidates) {
    const el = page.locator(selector);
    if ((await el.count()) > 0) return el.first();
  }
  return page.locator(candidates[0]).first();
}

test('recorded user flow', async ({ page }) => {
  if (START_URL) await page.goto(START_URL, { waitUntil: 'domcontentloaded' });

  // Step 1 — click | p | text="Find out where you stand among peers"
  const el1 = await resolveLocator(page, 'step_01KQ4YMNNNHP2XBSNJ2R7DNS24');
  await el1.click({ timeout: 15000 });

  // Step 2 — click | img | id="MzIwMToxOTg=-1"
  const el2 = await resolveLocator(page, 'step_01KQ4YMQKYF6V6BA3FR4QE1HZQ');
  await el2.click({ timeout: 15000 });

  // Step 3 — click | html | text="We use cookies to enable the best possib"
  const el3 = await resolveLocator(page, 'step_01KQ4YN1J1J6TDCM6RX06H1E3R');
  await el3.click({ timeout: 15000 });

  // Step 4 — click | path | id="Icon_material-close"
  const el4 = await resolveLocator(page, 'step_01KQ4YN343AAVMTCSFDRAXJF6X');
  await el4.click({ timeout: 15000 });

});